name: Sync Fork with Upstream Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Ceci vérifie les modifications toutes les 30 minutes. Ajustez selon vos besoins.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout forked repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Config Git
      run: |
        git config user.name 'Jam-automation'
        git config user.email 'dev.jam.solidaire@gmail.com'
    
    - name: Add remote upstream
      run: git remote add upstream https://github.com/dev-jam-solidaire/dev_app_flutter.git
      
    - name: Fetch changes from upstream
      run: git fetch upstream

    - name: Merge changes from upstream to main
      run: git merge upstream/flutterflow flutterflow

    - name: Push changes to forked repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'flutterflow'  # Assurez-vous que cela correspon
