name: Automate Pull Request

on:
  push:
    branches:
      - flutterflow

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Git
        run: |
          git config --global user.name 'JAM-automation'
          git config --global user.email 'dev.jam.solidaire@gmail.com'

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "flutterflow"
          destination_branch: "flutterflow"  # La branche dans le dépôt de base où les modifications doivent être fusionnées
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automated Pull Request from Fork"
          pr_body: "Une description de votre PR"
          pr_label: "automated-pr"  # Labels pour la PR, si nécessaire
